name: Test
on:
  push:

jobs:
  test:
    name: Create directory
    runs-on: ubuntu-latest
    env:
      GAC_FILE: credentials.json
      GAC_DIR: .secrets
    steps:
      - name: Create Google credentials file
        uses: jsdaniell/create-json@1.2.1
        with:
          name: ${{ env.GAC_FILE }}
          json: ${{ secrets.GCP_CREDENTIALS }}
          dir: ${{ env.GAC_DIR }}

      - name: Add required environment variables
        env:
          GAC: 
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GAC_DIR/$GAC_FILE" >> .Renviron
          ls -la
          cat "$GAC_DIR/$GAC_FILE"
